qt4-4.8.7: fix build for mips n32
Issue: LIN8-1720

If _ABIN32 is defined, it should go into 32 bit branch.

Fixed:
./wtf/StdLibExtras.h: In instantiation of 'TO WTF::bitwise_cast(FROM) [with TO = int; FROM = double]':
runtime/JSValueInlineMethods.h:495:44:   required from here
./wtf/Assertions.h:326:47: error: size of array is negative
 #define COMPILE_ASSERT(exp, name) typedef int dummy##name [(exp) ? 1 : -1]

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>