qt4-native: disable precompiled headers
Using precompiled headers may lead to errors in parallel builds:

| In file included from <command-line>:0:0:
| /usr/include/stdc-predef.h:59:1: error: one or more PCH files were found, but they were invalid
|  #endif
|  ^
| /usr/include/stdc-predef.h:59:1: error: use -Winvalid-pch for more information
| /usr/include/stdc-predef.h:59:1: fatal error: .pch/release-shared-emb-x86_64/QtCore: No such file or directory

Upstream bug report:
http://lists.qt-project.org/pipermail/development/2014-July/017689.html

Precompiled headers have been disabled for target builds from
the beginning (commit 46bdf066 in OE-Core).

Signed-off-by: Andreas Oberritter <obi@opendreambox.org>